// Auto-generated by LibreLane
module i2c_master_controller_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  inout io_scl,
  inout io_sda,
  output o_int_n,
  input[6:0] i_slave_addr_reg,
  input[7:0] i_byte_cnt_reg,
  input[7:0] i_clk_div_lsb,
  input[5:0] i_config_reg,
  input[7:0] i_mode_reg,
  output[7:0] o_cmd_status_reg,
  output o_start_ack,
  input[7:0] i_transmit_data,
  output o_transmit_data_request,
  output o_received_data_valid,
  output[7:0] o_receive_data,
  input i_rst_n,
  input i_clk
);
endmodule
