###############################################################################
# Created by write_sdc
###############################################################################
current_design i2c_master_controller_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name i_clk -period 32.0000 [get_ports {i_clk}]
set_clock_transition 0.1500 [get_clocks {i_clk}]
set_clock_uncertainty 0.2500 i_clk
set_propagated_clock [get_clocks {i_clk}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_byte_cnt_reg[0]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_byte_cnt_reg[1]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_byte_cnt_reg[2]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_byte_cnt_reg[3]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_byte_cnt_reg[4]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_byte_cnt_reg[5]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_byte_cnt_reg[6]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_byte_cnt_reg[7]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_clk_div_lsb[0]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_clk_div_lsb[1]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_clk_div_lsb[2]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_clk_div_lsb[3]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_clk_div_lsb[4]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_clk_div_lsb[5]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_clk_div_lsb[6]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_clk_div_lsb[7]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_config_reg[0]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_config_reg[1]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_config_reg[2]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_config_reg[3]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_config_reg[4]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_config_reg[5]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode_reg[0]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode_reg[1]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode_reg[2]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode_reg[3]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode_reg[4]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode_reg[5]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode_reg[6]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode_reg[7]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_rst_n}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_slave_addr_reg[0]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_slave_addr_reg[1]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_slave_addr_reg[2]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_slave_addr_reg[3]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_slave_addr_reg[4]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_slave_addr_reg[5]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_slave_addr_reg[6]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_transmit_data[0]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_transmit_data[1]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_transmit_data[2]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_transmit_data[3]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_transmit_data[4]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_transmit_data[5]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_transmit_data[6]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_transmit_data[7]}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {io_scl}]
set_input_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {io_sda}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {io_scl}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {io_sda}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_cmd_status_reg[0]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_cmd_status_reg[1]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_cmd_status_reg[2]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_cmd_status_reg[3]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_cmd_status_reg[4]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_cmd_status_reg[5]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_cmd_status_reg[6]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_cmd_status_reg[7]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_int_n}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_receive_data[0]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_receive_data[1]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_receive_data[2]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_receive_data[3]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_receive_data[4]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_receive_data[5]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_receive_data[6]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_receive_data[7]}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_received_data_valid}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_start_ack}]
set_output_delay 6.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_transmit_data_request}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {io_scl}]
set_load -pin_load 0.0334 [get_ports {io_sda}]
set_load -pin_load 0.0334 [get_ports {o_int_n}]
set_load -pin_load 0.0334 [get_ports {o_received_data_valid}]
set_load -pin_load 0.0334 [get_ports {o_start_ack}]
set_load -pin_load 0.0334 [get_ports {o_transmit_data_request}]
set_load -pin_load 0.0334 [get_ports {o_cmd_status_reg[7]}]
set_load -pin_load 0.0334 [get_ports {o_cmd_status_reg[6]}]
set_load -pin_load 0.0334 [get_ports {o_cmd_status_reg[5]}]
set_load -pin_load 0.0334 [get_ports {o_cmd_status_reg[4]}]
set_load -pin_load 0.0334 [get_ports {o_cmd_status_reg[3]}]
set_load -pin_load 0.0334 [get_ports {o_cmd_status_reg[2]}]
set_load -pin_load 0.0334 [get_ports {o_cmd_status_reg[1]}]
set_load -pin_load 0.0334 [get_ports {o_cmd_status_reg[0]}]
set_load -pin_load 0.0334 [get_ports {o_receive_data[7]}]
set_load -pin_load 0.0334 [get_ports {o_receive_data[6]}]
set_load -pin_load 0.0334 [get_ports {o_receive_data[5]}]
set_load -pin_load 0.0334 [get_ports {o_receive_data[4]}]
set_load -pin_load 0.0334 [get_ports {o_receive_data[3]}]
set_load -pin_load 0.0334 [get_ports {o_receive_data[2]}]
set_load -pin_load 0.0334 [get_ports {o_receive_data[1]}]
set_load -pin_load 0.0334 [get_ports {o_receive_data[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_scl}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_sda}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_byte_cnt_reg[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_byte_cnt_reg[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_byte_cnt_reg[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_byte_cnt_reg[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_byte_cnt_reg[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_byte_cnt_reg[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_byte_cnt_reg[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_byte_cnt_reg[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk_div_lsb[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk_div_lsb[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk_div_lsb[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk_div_lsb[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk_div_lsb[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk_div_lsb[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk_div_lsb[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk_div_lsb[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_config_reg[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_config_reg[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_config_reg[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_config_reg[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_config_reg[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_config_reg[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode_reg[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode_reg[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode_reg[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode_reg[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode_reg[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode_reg[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode_reg[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode_reg[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_slave_addr_reg[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_slave_addr_reg[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_slave_addr_reg[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_slave_addr_reg[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_slave_addr_reg[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_slave_addr_reg[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_slave_addr_reg[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_transmit_data[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_transmit_data[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_transmit_data[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_transmit_data[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_transmit_data[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_transmit_data[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_transmit_data[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_transmit_data[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
